CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar NOT NULL,
  "age" integer NOT NULL
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "level" integer NOT NULL,
  "teacher" integer NOT NULL
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL
);

CREATE TABLE "Course_video" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" integer NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "course_id" integer NOT NULL
);

CREATE TABLE "roles_users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL
);

CREATE TABLE "user_courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "course_id" integer NOT NULL
);

CREATE TABLE "level" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "user_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "Course_video" ADD FOREIGN KEY ("title") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");




INSERT INTO users (name,password,email,age)  VALUES ('jabid','jjsg1234','jabidjunior@gmail.com','21');

INSERT INTO users (name,password,email,age)  VALUES ('Andrés','asg1234','andresgomez@gmail.com','30');

INSERT INTO users (name,password,email,age)  VALUES ('Ana','ana1234','anasuarez@gmail.com','25');

INSERT INTO level (name) VALUES ('Beginner'), ('Intermediate'), ('Advance');

INSERT INTO roles (title) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO categories (name) VALUES ('Technology'), ('Programming'), ('Development');

INSERT INTO roles_users (user_id,role_id) VALUES (1,1),(2,2),(3,3);

INSERT INTO courses (title,description,level,teacher) VALUES ('Introducción a REACT', 'En este curso se aprenderán las bases de REACT',1,2);

 INSERT INTO courses (title,description,level,teacher) VALUES ('Introducción a Node.JS', 'En este curso se aprenderán las bases de Node.JS',2,2);

 INSERT INTO courses (title,description,level,teacher) VALUES ('Introducción a Express.JS', 'En este curso se aprenderán las bases de Express.JS',3,2);

 INSERT INTO courses_categories (category_id,course_id) VALUES (1,1), (2,2), (3,3);

 INSERT INTO user_courses (user_id,course_id) VALUES (2,1),(2,2),(2,3),(1,1),(1,2),(1,3);

  INSERT INTO "Course_video" (title,url) VALUES (1,'URL1 curso uno'), (2,'URL1 curso dos'), (3,'URL1 curso tres');